### ISSUE TITLE
apply vs rowSums, colSums

### ISSUE THREAD

**Issue by zx8754** [knausb/vcfR_documentation#1]
Minor issue, I am going through the docs (https://knausb.github.io/vcfR_documentation/index.html), and noticed we are using `apply `where we could use simpler functions, e.g.:

for example this:
```R
myMiss <- apply(dp, MARGIN = 2, function(x){ sum(is.na(x)) })
myMiss <- myMiss/nrow(vcf)
```

could be replaced with this:
```R
myMiss <- colSums(is.na(dp))/nrow(vcf)
```

Similar approach used in "Apply" page, maybe it is OK as a demonstration of apply function, but if it is about sums then better to use dedicated function `rowSums `and `colSums`

**Comment by knausb** [comment]
This is an arbitrary distinction. Neither way is better than the other. In fact, some may be of the perspective that if you can learn a general tool such as `apply()` you won't need these simpler functions. I think its good to get people using `apply()` even on simple applications because then they will have this skill when they have more complicated tasks at hand.

**Comment by zx8754** [comment]
`rowSums` is about 8 times faster than `apply`. But yes, agree, maybe good way to learn how to use `*apply` functions.
